apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oncallm.fullname" . }}-secret
  labels:
    {{- include "oncallm.labels" . | nindent 4 }}
# The secret is of type Opaque and stores base64-encoded values supplied through Helm values
# NOTE: Set the real values through --set or a values file when installing/upgrading the chart.
# Example:
# helm install oncallm ./charts/oncallm \
#   --namespace monitoring \
#   --set openaiApiKey="YOUR_API_KEY" \
#   --set llmApiBase="https://api.example.com/openai"

type: Opaque
data:
  {{- if .Values.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.openaiApiKey | b64enc }}
  {{- end }}
  {{- if .Values.langfusePublicKey }}
  LANGFUSE_PUBLIC_KEY: {{ .Values.langfusePublicKey | b64enc }}
  {{- end }}
  {{- if .Values.langfuseSecretKey }}
  LANGFUSE_SECRET_KEY: {{ .Values.langfuseSecretKey | b64enc }}
  {{- end }}
  {{- if .Values.langfuseHost }}
  LANGFUSE_HOST: {{ .Values.langfuseHost | b64enc }}
  {{- end }}
